@startuml ex08

skinparam dpi 300

class Terran {
    -#name: string
    -#hp: number
    -#dps: number
    +<<constructor>> constructor (name: string, hp: number, dps: number)
    +<<get/set>> name()
    +<<get/set>> hp()
    +<<get/set>> dps()
    +move(position: string): void
    +attack(target: string): void
}

class Marine {
    +attack(target: string): void
}

class Tank {
    +attack(target: string): void
}

Terran <|-- Marine
Terran <|-- Tank

@endumls